include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v15.9.0
  #
stages:
  - register
  - backup
  - download
  - ingest
  - analyse

Register image:
  stage: register
  extends: .base_register_stage
  only:
    - master
  variables:
    CONTEXT: . # The folder where the Dockerfile is
    IMAGE_NAME: $CI_REGISTRY_IMAGE # The image name

Backup Matomo data:
  stage: backup
  image: mcr.microsoft.com/azure-cli
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  only:
    variables:
      - $TYPE == "ingestion"
  script:
    - AZ_STORAGE_TOKEN=$AZ_STORAGE_TOKEN bash ./scripts/dump_matomo_yesterday.sh

Download dump from Azure:
  stage: download
  image: mcr.microsoft.com/azure-cli
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  only:
    variables:
      - $TYPE == "ingestion"
  script:
    - AZ_STORAGE_TOKEN=$AZ_STORAGE_TOKEN bash ./scripts/download_dump.sh
  artifacts:
    paths:
      - data/
    expire_in: 1 hour

Ingest to ES:
  stage: ingest
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  only:
    variables:
      - $TYPE == "ingestion"
  artifacts:
    paths:
      - data/
    expire_in: 1 hour
  variables:
    MONOLOG_ACTION: $TYPE
    DATA: "data/"

Run analysis:
  stage: analyse
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  only:
    variables:
      - $TYPE == "analyse"
  variables:
    MONOLOG_ACTION: $TYPE
