include:
  - project: SocialGouv/gitlab-ci-yml
    file: /base_register_stage.yml
    ref: v15.7.0
  - /.gitlab-ci/stages/register.yml
  - /.gitlab-ci/stages/backup.yml
  - /.gitlab-ci/stages/download.yml
  - /.gitlab-ci/stages/ingest.yml
  #
stages:
  - register
  - backup
  - download
  - ingest
