Ingest to ES:
  stage: ingest
  image: $CI_REGISTRY_IMAGE:master
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  variables:
    MONOLOG_ACTION: ingest
  artifacts:
    paths:
      - ./data
    expire_in: 1 hour
