Ingest to ES:
  stage: ingest
  image: $CI_REGISTRY_IMAGE:master
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  artifacts:
    paths:
      - ./data
    expire_in: 1 hour
  script:
    - ELASTICSEARCH_URL=$ELASTICSEARCH_URL API_KEY=$API_KEY MONOLOG_ACTION=ingest node -r esm src/index.js
