Ingest to ES:
  stage: ingest
  image: $CI_REGISTRY_IMAGE:ci-xp
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: manual
  variables:
    MONOLOG_ACTION: ingest
  artifacts:
    paths:
      - ./data
    expire_in: 1 hour
  # script:
  # - ELASTICSEARCH_URL=$ELASTICSEARCH_URL API_KEY=$API_KEY MONOLOG_ACTION=ingest node index.js
